export const config = {
  logo: "YOUR_LOGO_URL_HERE",
  siteName: "KBC Quiz AI",
  adminEmail: "YOUR_ADMIN_EMAIL_HERE",
  adSenseAccount: "ca-pub-8228784571140150",
  siteVerification: "YOUR_GOOGLE_VERIFICATION_CODE",
  apiUrl: import.meta.env.VITE_API_URL || "",
  firebase: {
    apiKey: "AIzaSyCuZDyri0F0ky2sHxFO-p2OKvEB2sQfihw",
    authDomain: "dreamdrop-3ca3d.firebaseapp.com",
    databaseURL: "https://dreamdrop-3ca3d-default-rtdb.firebaseio.com",
    projectId: "dreamdrop-3ca3d",
    storageBucket: "dreamdrop-3ca3d.firebasestorage.app",
    messagingSenderId: "882827368473",
    appId: "1:882827368473:web:bf146e6c9f5db32edbb288",
    measurementId: "G-Z6B3CZZRC9",
  },
  razorpay: { keyId: "YOUR_RAZORPAY_KEY_ID" },
  premium: {
    weekly: { price: 1900, label: "Weekly ₹19", days: 7 },
    monthly: { price: 4900, label: "Monthly ₹49", days: 30 },
    yearly: { price: 29900, label: "Yearly ₹299", days: 365 },
  },
  moneyLadder: [1000,2000,3000,5000,10000,20000,40000,80000,160000,320000,640000,1250000,2500000,5000000,10000000],
  categories: [
    { id: "gaming", label: "Gaming", icon: "🎮", prompt: "Generate a multiple choice question about PC gaming, console gaming, video games, esports, or gaming hardware. Mix Hindi and English naturally." },
    { id: "gk", label: "General Knowledge", icon: "🧠", prompt: "Generate a multiple choice question about Indian history, geography, science, or current affairs. Mix Hindi and English naturally." },
    { id: "bollywood", label: "Bollywood", icon: "🎬", prompt: "Generate a multiple choice question about Bollywood movies, actors, songs, or directors from 2000-2024." },
    { id: "sports", label: "Sports", icon: "🏏", prompt: "Generate a multiple choice question about cricket, football, kabaddi, or Indian sports history." },
    { id: "tech", label: "Technology", icon: "💻", prompt: "Generate a multiple choice question about technology, smartphones, internet, or social media. Beginner to intermediate level." },
    { id: "finance", label: "Finance", icon: "💰", prompt: "Generate a multiple choice question about basic finance, stock market, banking, or Indian economy. Beginner level." },
  ],
  eventTypes: [
    { id: "basic", label: "Basic", icon: "🥉", color: "#cd7f32", questions: 10, multiplier: 1, reward: "Badge", timerSec: 30 },
    { id: "standard", label: "Standard", icon: "🥈", color: "#c0c0c0", questions: 20, multiplier: 2, reward: "₹50–₹100 Gift Card", timerSec: 20 },
    { id: "advanced", label: "Advanced", icon: "🥇", color: "#ffd700", questions: 30, multiplier: 3, reward: "₹200–₹500 Cash", timerSec: 15 },
    { id: "elite", label: "Elite", icon: "👑", color: "#9b59b6", questions: 50, multiplier: 5, reward: "₹1000+ Prize", timerSec: 10 },
    { id: "tournament", label: "Tournament", icon: "🏆", color: "#e74c3c", questions: 100, multiplier: 10, reward: "Grand Prize", timerSec: 10 },
  ],
};
